name: estacio-trabalho

services:
  backend:
    hostname: estacio.backend
    container_name: estacio_backend
    image: estacio/backend
    build:
      context: .
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/app
    privileged: true
    ports:
      - $BACKEND_PORT:$BACKEND_PORT
    networks:
      - estacio-net
  database:
    hostname: estacio.mongo
    image: mongo:8.0.3
    restart: always
    container_name: $DATABASE_HOST
    command: --port $DATABASE_PORT --bind_ip_all
    ports:
      - $DATABASE_PORT:$DATABASE_PORT
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DATABASE_USER
      MONGO_INITDB_ROOT_PASSWORD: $DATABASE_PASSWORD
    healthcheck:
      test: mongosh mongodb://$DATABASE_USER:$DATABASE_PASSWORD@0.0.0.0:$DATABASE_PORT --eval 'db.runCommand("ping").ok'
      timeout: 10s
      retries: 4
    networks:
      - estacio-net
    volumes:
      - db:/data/db
  mongo-express:
    hostname: estacio.express
    image: mongo-express
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_EXPRESS_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_EXPRESS_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/
      ME_CONFIG_BASICAUTH: false
    networks:
     - estacio-net
networks:
  estacio-net:
    name: estacio-net
    # ipam:
    #   config:
    #     - subnet: 192.168.3.0/28
    # driver: bridge

volumes:
  db:
    name: volume-mongo-backend
    
  
      